// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT1nemwxq8DgRUgtpWL5Hb-IZoBchGvCU',
    appId: '1:360868953226:web:6267df7e0a6f7cab4cc173',
    messagingSenderId: '360868953226',
    projectId: 'flutter-media-prod',
    authDomain: 'flutter-media-prod.firebaseapp.com',
    storageBucket: 'flutter-media-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrGzmi2Fk-iEkx-qeY7DRFSSLjZfYj-0A',
    appId: '1:360868953226:android:c3f003ae179bd3214cc173',
    messagingSenderId: '360868953226',
    projectId: 'flutter-media-prod',
    storageBucket: 'flutter-media-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo_p-_iE7Czn55aYVJZQmXdKNf9fstgi0',
    appId: '1:360868953226:ios:a3a1a8dd8ec9cf114cc173',
    messagingSenderId: '360868953226',
    projectId: 'flutter-media-prod',
    storageBucket: 'flutter-media-prod.firebasestorage.app',
    iosClientId: '360868953226-g99naq24gbjjjddihj94grm60p840a2b.apps.googleusercontent.com',
    iosBundleId: 'com.thang.flutterSocialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo_p-_iE7Czn55aYVJZQmXdKNf9fstgi0',
    appId: '1:360868953226:ios:a3a1a8dd8ec9cf114cc173',
    messagingSenderId: '360868953226',
    projectId: 'flutter-media-prod',
    storageBucket: 'flutter-media-prod.firebasestorage.app',
    iosClientId: '360868953226-g99naq24gbjjjddihj94grm60p840a2b.apps.googleusercontent.com',
    iosBundleId: 'com.thang.flutterSocialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT1nemwxq8DgRUgtpWL5Hb-IZoBchGvCU',
    appId: '1:360868953226:web:df30692ffefb62874cc173',
    messagingSenderId: '360868953226',
    projectId: 'flutter-media-prod',
    authDomain: 'flutter-media-prod.firebaseapp.com',
    storageBucket: 'flutter-media-prod.firebasestorage.app',
  );

}