// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATNb9cqcMzANWCx9Sgyl1AYjAuKy0hOQY',
    appId: '1:265497588234:web:6f95549305050fa8e3a5f3',
    messagingSenderId: '265497588234',
    projectId: 'flutter-media-stg',
    authDomain: 'flutter-media-stg.firebaseapp.com',
    storageBucket: 'flutter-media-stg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR1NhMGK31fctpspfxEPxUtwKQp6stGyA',
    appId: '1:265497588234:android:af40b4e093781a96e3a5f3',
    messagingSenderId: '265497588234',
    projectId: 'flutter-media-stg',
    storageBucket: 'flutter-media-stg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCriRq9I3JvS_DoVTmQIcAY-Hb9AfRZhwM',
    appId: '1:265497588234:ios:e6656871fde42524e3a5f3',
    messagingSenderId: '265497588234',
    projectId: 'flutter-media-stg',
    storageBucket: 'flutter-media-stg.firebasestorage.app',
    iosClientId: '265497588234-7veb6qn6a32udava7mpgjj58pjdqkotf.apps.googleusercontent.com',
    iosBundleId: 'com.thang.flutterSocialMedia.stg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCriRq9I3JvS_DoVTmQIcAY-Hb9AfRZhwM',
    appId: '1:265497588234:ios:e6656871fde42524e3a5f3',
    messagingSenderId: '265497588234',
    projectId: 'flutter-media-stg',
    storageBucket: 'flutter-media-stg.firebasestorage.app',
    iosClientId: '265497588234-7veb6qn6a32udava7mpgjj58pjdqkotf.apps.googleusercontent.com',
    iosBundleId: 'com.thang.flutterSocialMedia.stg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATNb9cqcMzANWCx9Sgyl1AYjAuKy0hOQY',
    appId: '1:265497588234:web:f1b3a2870237b801e3a5f3',
    messagingSenderId: '265497588234',
    projectId: 'flutter-media-stg',
    authDomain: 'flutter-media-stg.firebaseapp.com',
    storageBucket: 'flutter-media-stg.firebasestorage.app',
  );
}
