// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK6dGX4N9hzI_YsI0RELWwsQ3XzMnXKUE',
    appId: '1:194799561750:web:e986127f4ef5f862701937',
    messagingSenderId: '194799561750',
    projectId: 'flutter-media-dev',
    authDomain: 'flutter-media-dev.firebaseapp.com',
    storageBucket: 'flutter-media-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkeyoX3Zmrt-M9Azv1JpVBCKVqJEGEvOQ',
    appId: '1:194799561750:android:9703c157f4146267701937',
    messagingSenderId: '194799561750',
    projectId: 'flutter-media-dev',
    storageBucket: 'flutter-media-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwlF3e8IxJflIP5gZgOIIp-bHcZkxAmIs',
    appId: '1:194799561750:ios:cacfda258ec9ad62701937',
    messagingSenderId: '194799561750',
    projectId: 'flutter-media-dev',
    storageBucket: 'flutter-media-dev.firebasestorage.app',
    iosClientId: '194799561750-520jf2fbu652lh3d32i37f82nojn98tn.apps.googleusercontent.com',
    iosBundleId: 'com.thang.flutterSocialMedia.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwlF3e8IxJflIP5gZgOIIp-bHcZkxAmIs',
    appId: '1:194799561750:ios:cacfda258ec9ad62701937',
    messagingSenderId: '194799561750',
    projectId: 'flutter-media-dev',
    storageBucket: 'flutter-media-dev.firebasestorage.app',
    iosClientId: '194799561750-520jf2fbu652lh3d32i37f82nojn98tn.apps.googleusercontent.com',
    iosBundleId: 'com.thang.flutterSocialMedia.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK6dGX4N9hzI_YsI0RELWwsQ3XzMnXKUE',
    appId: '1:194799561750:web:8d62a7908dfefbd0701937',
    messagingSenderId: '194799561750',
    projectId: 'flutter-media-dev',
    authDomain: 'flutter-media-dev.firebaseapp.com',
    storageBucket: 'flutter-media-dev.firebasestorage.app',
  );
}
